### ISSUE TITLE
Замечания от Виноградова

### ISSUE THREAD

**Issue by ppv-mipt** [altavir/mipt-stat-book#10]
- Обосновать правила округления -- почему до 2х значащих цифр?
- Рассмотреть ситуацию, когда измерения ведутся прибором со значительной систематической погрешностью, а случайная погрешность мала

**Comment by ppv-mipt** [comment]
Мои предложения

* Вставить пункт "погрешность погрешности" в Приложение.
* Расширить пример "недооценка систематической погрешности" из п. 4.4. В духе примера обработки 1.1.1: https://mipt.ru/education/chair/physics/S_I/lab/example.pdf

Можно последнее представить как случай, когда ошибки коррелированы и пропорциональны значению измеряемой величины.

**Comment by altavir** [comment]
По поводу округления ничего не знаю, вопрос эстетический.
По поводу вопроса номер 2, тут все не так просто. Это не погрешность погрешности, а одностороннее смещение. Там надо разбирать случай скоррелированных и нескоррелированных  смещений отдельно. Я не уверен, что мы сможем не нарушая простоты втиснуть в пособие. Можно добавить note и пример на эту тему.

**Comment by ppv-mipt** [comment]
Погрешность погрешности -- это как раз к вопросу об округлении.

Касательно N2. Предлагаю разобрать один пример, где все отклонения смещены пропорционально значению величины: $\Delta y = k y$, где k -- некоторая неизвестная константа (то есть слегка уплыл коэффициент пропорциональности между измеряемой величиной и показаниями прибора). Насколько я понял, именно это хочет видеть Виноградов (и не только).

**Comment by altavir** [comment]
Округление - это не погрешность. Округлять можно только при представлении результата. Досрочное округление производится только если заведомо известно, что это превышение точности.

У меня в лекциях есть примеры, я завтра добавлю, но там тогда надо сразу добавлять несколько.

**Comment by ppv-mipt** [comment]
Округление погршености при представлении результата производится потому, что представлять результат в более точном виде бессмысленно. А именно, нет смысла записывать погрешность точнее, чем её погрешность (см. например Сквайрс, Гл. 2, п. 6.)

**Comment by altavir** [comment]
Это все ясно, но округление само собой не является погрешностью. Если есть сноска об этом - этого достаточно. Рассматривать погрешность как случайную величину со своей погрешностью - это для данного пособия превышение точности (кстати как и коэффициенты Стьюдента, которые относятся к той же теме).

**Comment by ppv-mipt** [comment]
Ну никто и не говорил, что округление -- это погрешность. Думаю, достаточно будет добавить замечание и ссылку на литературу.

**Comment by altavir** [comment]
Добавил два примера: https://github.com/altavir/mipt-stat-book/commit/3a683341927be95747a1947787fc81d6169e00f2 и https://github.com/altavir/mipt-stat-book/commit/bfff7a51d313124005402f01fb182bde7a0b4a22

**Comment by altavir** [comment]
Это можно закрыть?

**Comment by ppv-mipt** [comment]
Закрываем.
