### ISSUE TITLE
Определение случайной величины.

### ISSUE THREAD

**Issue by ppv-mipt** [altavir/mipt-stat-book#11]
Предлагаю смягчить культурный шок от определения случайной величины.

Вместо 
> Случайной будем называть величину, значение которой не может быть
достоверно определено экспериментатором с абсолютной точностью или
значение которой меняется в каждом последующем опыте неконтроли-
руемым образом. Согласно такому определению, любой результат любых
измерений является случайным, поскольку осведомленность эксперимен-
татора всегда чем-то ограничена.

> Замечание. Хотя понятия вероятности и случайной величины являются
основополагающими, в литературе нет единства в их определении. Об-
суждение формальных тонкостей или построение строгой теории лежит
за пределами данного пособия. Наша цель — дать упрощенное, но нагляд-
ное представление о предмете. Заинтересованным читателям рекомендуем
обратиться к специальной литературе: [5].

Вставить следующее

"""
Случайной будем называть величину, значение которой меняется в каждом последующем измерении неконтролируемым образом.

Замечание. Поскольку конкретная величина погрешности никогда не известна, 
результат *любого* измерения можно считать случайным: даже если погрешность имеет систематический характер, можно считать, что ее величина была определена по некоторому случайному закону перед началом измерений (например, при изготовлении линейки на заводе произошло некоторое случайное искажение шкалы).  Более подробное обсуждение различных трактовок понятий вероятность и случайная величина можно найти в специальной литературе [5].
"""

При этом можно сократить замечание в п. 2.5, как дублирующее.

**Comment by altavir** [comment]
> значение которой меняется в каждом последующем измерении неконтролируемым образом

Ну это заведомо плохое определение, поскольку не всегда есть последующее измерение. Как правило каждый эксперимент уникален. Это классическая ловушка, в которую попадают при переходе от математического частотного определения к реальности. Для младших курсов конечно не важно, но мне кажется, что надо давать определения таким образом, чтобы потом можно было получить выводы самостоятельно.

**Comment by ppv-mipt** [comment]
Если эксперимент "уникален", то рассуждения о вероятностях -- это *домыслы*, основанные либо а) на неявно сделанных предположениях, заимствованных из других экспериментов, б) ни на чем (авось ошибка да гауссова).

Конечно, есть субъективная трактовка вероятности и все ей пользуются (по указанным выше причинам). И мы сделаем по этому поводу замечание и дадим отсылку к серьезным книжкам. Но по-моему, на младших курсах куда важнее, чтобы мир был простым и понятным. Поэтому "хорошее" определение на младших курсах должно быть прозрачным и не должно вызывать лишних вопросов. Подробное же разъяснение субъективного смысла вероятности в рамках пособия завело бы нас слишком далеко -- и сильно отдалило бы от главного (а главное заявлено в предисловии -- минимальные практические рекомендации для корректной обработки данных).

Кроме того, лично я не вижу в использовании частотного определения препятствий к получению каких-либо выводов. По-моему, это чем-то похоже на спор об интерпретациях квантовой механики: люди произносят сильно разные слова над одними и теми же формулами -- и получают одни и те же результаты. Возможно, Вы разубедите меня, приведя пример?

**Comment by altavir** [comment]
Это безусловно аналогично интерпретации квантовой механики. Результат одинаковый. Другое дело, что для получения формально того же результата в частотной интерпретации надо говорить на порядок больше слов. Я думаю, что расхождение мнений идет на вот этом этапе:

>Но по-моему, на младших курсах куда важнее, чтобы мир был простым и понятным. 

Но это опять же идейный момент. Я подумаю про компромиссный вариант. Вчера к сожалению так и не добрался. Постараюсь завтра.

**Comment by altavir** [comment]
Компромиссный вариант: https://github.com/altavir/mipt-stat-book/commit/03a6d8a9176365102c2f25480c07bc1b6ea45b1f

**Comment by ppv-mipt** [comment]
Еще более компромиссный вариант https://github.com/mipt-npm/mipt-stat-book/commit/d4ab20028089e0e3a2d2ee19e4220e3ab24635f2
