### ISSUE TITLE
Сокращение до 48 стр.

### ISSUE THREAD

**Issue by ppv-mipt** [altavir/mipt-stat-book#13]
Подогнать под регламентированный размер учебно-методическоо пособия в 48 страниц.

Предлагаю форк на две версии: издательскую и режиссерскую.

План работ по издательской версии:

* причесать стиль 
* утрамбовать форматирование
* отрезать Приложение
* убрать "лишние" замечания
* убрать что-нибудь важное (что?)

**Comment by altavir** [comment]
`Давайте отрежем удаву гланды`. Теоретических возражений не имею кроме того, что поддерживать две версии - это можно убиться. Надо тогда ввести окружение или команду для того, что будет выкинуто из "короткой" версии для того, чтобы был единый код. При наличии ключа содержимое вырезается, без - остается. Тот же ключ использовать для параметров форматирования.

**Comment by ppv-mipt** [comment]
Поскольку при издательстве в любом случае необходима тонкая доработка напильником (с прямой правкой форматирования), я не уверен в целесообразности введения отдельной команды.
Предлагаю делать издательскую версию один раз (что напечатано станком - то не вырубишь топором). А развивать режиссерскую.

**Comment by altavir** [comment]
Я имею в виду, что не надо плодить вариантов, а то потом надо будет вносить правки в два экземпляра. Все равно надо будет отдавать на вычитку.

**Comment by ppv-mipt** [comment]
Процесс утрамбовки идет в ветке press.

**Comment by ppv-mipt** [comment]
Утрамбовано в первом приближении.
