### ISSUE TITLE
Знак для усреднения

### ISSUE THREAD

**Issue by altavir** [altavir/mipt-stat-book#8]
Решить, как рисуем усреднение. Я считаю, что должно быть `<>` везде, чтобы не путать с векторами.

**Comment by ppv-mipt** [comment]
Выборочное среднее и среднее по распределению (оно же предельное) должны обозначаться разными символами (соответственно, есть угловые скобки и черта). Векторов у нас в методичке нет. К тому же векторы по традиции выделяются жирным.

**Comment by altavir** [comment]
Мы должны выработать единые правила для всех наших пособий, иначе будет в одном месте так, в другом не так - бардак. Мешать свои обозначения с общепринятыми - тоже не хорошо. 
Предлагаю два альтернативных варианта:

* Среднее по распределению как правило обозначают как мат. ожидание $E[\theta]$.  

* Можно обозначать среднее по распределению $f$ как $<x>_f$

Еще у нас есть понятие оценки: $\hat{x}$

**Comment by ppv-mipt** [comment]
$E[\theta]$ -- слишком громоздко и страшно, и стиль не физический.

Если индекс, то разве что $x_0$ или $x_{ср}$.

Чем собственно плохо \overline?

**Comment by altavir** [comment]
Тем, что оно конфликтует с векторами (не здесь, но в физических книжках и в многомерном случае по статистике). Кроме того - мы тогда мешаем обозначения, что плохо. У вас по тексту оно используется два или три раза.

**Comment by ppv-mipt** [comment]
В русской традиции векторы в физических книжках выделяют жирным. А вот о многомерном случае статистики я пока не думал. Может там тоже жирным выделить?

**Comment by altavir** [comment]
Это не русская традиция, это физтеховская традиция, причем, по-моему, только на нашей кафедре. Вот попросил жену уточнить, она редактор. Насчет жирных векторов есть от людей много замечаний. Надо уже все унифицировать.

![image](https://user-images.githubusercontent.com/9514268/45361802-ca390580-b5db-11e8-988b-2b69741b37e1.png)

**Comment by ppv-mipt** [comment]
Нет, это не физтеховская традиция. Открыл навскидку первые попавшиеся учебники:
Савельев
Стрелков
Крауфорд
Ландау-Лифшиц
Джексон (Электродинамика)
Трубников (Теория плазмы)
Разные издательства: Наука, Физматлит, Атомиздат
Везде вектора жирные.

Книги с векторами-стрелочками где-то были, но быстро их найти не смог. Книг с векторами-черточками не встречал в принципе.

От каких людей есть много замечаний?

**Comment by altavir** [comment]
От студентов.

**Comment by ppv-mipt** [comment]
Студенты не хотят жирные векторы или хотят унификации?
